### ISSUE TITLE
Can't the RODE algorithm run in parallel?

### ISSUE THREAD

**Issue by jk96491** [TonghanWang/RODE#1]
Hello

I want to run RODE in parallel

However, looking at the code, the parallel execution side is not able to respond.

Is it impossible to run in parallel?

**Comment by TonghanWang** [comment]
Hi, we are sorry that we only prepare the `episode_runner`. And we recommend this runner for the SMAC benchmark.

The reason is that, typically, on SMAC, parallel environments will not improve the performance. For example, if you achieve 100% win rate using the episode_runner at 1M steps, you will get 100% at 8M if you use 8 parallel environments. This is the same for many popular algorithms, like QMIX, QPLEX, etc.

We will update the code to support `parallel_runner`. We will let you know as soon as we finish it. Sorry again for the inconvenience.

**Comment by jk96491** [comment]
TonghanWang //  

Thanks for the reply.!!!
Even if it takes a lot of time, it should be done by episode.

**Comment by TonghanWang** [comment]
You are welcome! I'd like to clarify one more thing that I didn't make it clear.

By the examples (1M steps vs. 8M steps) in the previous response, I mean it takes roughly the same time (wall clock) for both episode_runner and parallel runner to achieve the same win rate. If you use episode_runner, you only need to run 2M steps, while using 8 parallel environments, you roughly need 16M steps. 

I guess this is also the reason why other popular algorithms like QMIX use episode_runner too.
