### ISSUE TITLE
The version of StarCraft in Paper

### ISSUE THREAD

**Issue by deligentfool** [TonghanWang/RODE#5]
Hello!
Can I ask you what the version of StarCraft II is in your paper? Is it 4.10?

**Comment by deligentfool** [comment]
Sorry, I found it.
It is 4.10

**Comment by mamadpierre** [comment]
Where did you find it? The version of the StarCraft II?

**Comment by deligentfool** [comment]
Sorry, I got it wrong. I don't know the version. We need the author to answer us.

**Comment by mamadpierre** [comment]
As far as the paper goes, RODE authors stated, "We test RODE on StarCraft II micromanagement environments (Samvelyan et al., 2019)." In the Samvelyan github it says, " The results in SMAC (https://arxiv.org/abs/1902.04043) use SC2.4.6.2.69232 not SC2.4.10."

So, I would be surprised that the version be something rather than SC2.4.6.2.69232 but still I cannot find it in the RODE paper explicitly.

**Comment by deligentfool** [comment]
I run RODE on SC2.4.6.2.69232 but can not get the same performance. And I see the results of RODE in this paper(https://arxiv.org/abs/2010.04740) on SC2.4.10. I think the performance on SC2.4.10 is closer to the original paper than that on SC2.4.6.2.69232.
Did you run RODE on SC2.4.6.2.69232 and what's the result? This confused me for a long time.

**Comment by TonghanWang** [comment]
Hi all,

We run it on SC II 4.10. When we developing our algorithm, SC II upgrades and we change to the new version.

We cannot find our experiment results on SC II 4.6, but I remember that the results aew significantly different only on a few maps like 1c3s5z.

**Comment by deligentfool** [comment]
Thanks for your reply! It helps me a lot.
