### ISSUE TITLE
Does the hierarchical part (including role selector and role executor) keep updating during the phase one + the phase two period?

### ISSUE THREAD

**Issue by chaobiubiu** [TonghanWang/RODE#7]
Hello, when i read this code, i found that the role action space is initialized as ' torch.ones(n_roles, n_actions) ' at the training beginnning, which means that each role includes the whole action space initially. Then the role selector, role executor and the action encoder keep updating when ' t_env < self.args.role_action_spaces_update_start ', which refers to ' phase 1 ' in the RODE paper. And when t_env exceeds this time_limit, the action encoder is fixed and helps update the roles' action spaces. So I am confused whether the role selector and role executor have been updated during (2000000 + 50000) timesteps instead of 2000000 timesteps. I hope the author can answer this question, thank you.

**Comment by TonghanWang** [comment]
Hi! In phase 1, we set role action spaces to the full action spaces for more efficient sampling (so that the action encoder can be learned well). The role selector and role policies are updated during this phase, but we do not expect they learn the right role-based policy because we do know the true role action spaces at this time. Only after ` t_env > self.args.role_action_spaces_update_start `, ie, after role action spaces are updated, will the desired policies start to be trained.

**Comment by chaobiubiu** [comment]
Ok, thank you!
